config/routes.rb
LittlehumansApp::Application.routes.draw do

  resources :deliveries

  resources :rosters

  get "static_pages/about_us"
  get "static_pages/contact_us"
  get "static_pages/privacy"
  get "static_pages/terms_and_cond"
  get "static_pages/help"
  
  devise_for :users, 
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                               :registrations => "users/registrations", 
                               :passwords => 'users/passwords'
                             }

  # resources :users, :only => [:index, :show, :edit, :update]

  resources :users do
    resources :rosters
    resources :deliveries
  end

  resources :rosters do
    collection do
      post :new_event
      post :delete_event
    end
  end

  get "/dashboard" => "users#dashboard", :as => :dashboard

  devise_scope :user do
    root :to => "devise/sessions#new"
  # root :to => 'devise/sessions#new'
  #  get "/users/sign_in" => "devise/sessions#new", :as => :login
  #  get "/users/sign_up" => "devise/sessions#create", :as => :signup
  end

  # authenticated :user do
  #   root :to => "devise/sessions#new", :as => "authenticated_root"
  #   # Rails 4 users must specify the 'as' option to give it a unique name
  #   # root :to => "main#dashboard", :as => "authenticated_root"
  # end

  # tell devise to use scope users
  # devise_scope :user do
  #   root :to => 'devise/sessions#new'
  # end
end

app/models/roster.rb
class Roster < ActiveRecord::Base

  belongs_to :user
  has_many :deliveries

end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  #before_action :set_user, only: [:calendar]

  # displays iframe containing the Google Calendar named Littlehumans
  # GET /rosters
  # GET /rosters.json
  def index
    @rosters = current_user.rosters.all
  end

  # creates a new event on Google Calendar named 'Littlehumans'
  # POST /rosters/new_event
  def new_event
    @roster = current_user.rosters.new(roster_params)

    cal = ClientGoogleCalendar::client_google_calendar

    #logger.info("roster is *** #{@roster.to_json}")
    #logger.info("name_shift is *** #{@roster["name_shift"]}")
    event = cal.create_event do |e|
      e.title = @roster["name_shift"]
      e.where = @roster["name_location_shift"] + ", " + @roster["name_location_hospital"]
      e.start_time = @roster["time_shift_start"]
      e.end_time = @roster["time_shift_end"]
    end
    #logger.info("cal events is *** #{cal.events.to_json}") # display in rails console

    respond_to do |format|
        format.html { redirect_to user_path(current_user), :notice => 'calendar event created.' }
    end
  end

  # edit an existing event on Google Calendar named 'Littlehumans'
  # POST /rosters/edit_event
  def edit_event
    # parameters passed from _load_calendar.js.erb containing data json to edit the event with
    @roster = current_user.rosters.new(roster_params)
    @form_switch = "edit event"

    cal = ClientGoogleCalendar::client_google_calendar

    # find event id passed in 
    event = cal.find_or_create_event_by_id(@roster["name_shift"]) do |e|
      # edit the attributes of the event id similar to when creating an event
      #e.title = @roster["name_shift"]
      e.where = @roster["name_shift"]# + ", " + @roster["name_location_hospital"]
      #e.start_time = @roster["time_shift_start"]
      #e.end_time = @roster["time_shift_end"]
    end

    respond_to do |format|
        format.html { redirect_to user_path(current_user), :notice => 'calendar event updated.' }
    end
  end

  # delete an event from Google Calendar named Littlehumans
  def delete_event
    # parameter passed from _load_calendar.js.erb containing data json with event id to delete 
    @roster = current_user.rosters.new(roster_params)

    cal = ClientGoogleCalendar::client_google_calendar

    # find event id 
    event_id = @roster["name_shift"]
    event = cal.find_or_create_event_by_id(event_id)

    cal.delete_event(event)

    respond_to do |format|
        format.json { render :json => @url_resp.to_json }
        format.html { redirect_to user_path(current_user), :notice => 'httparty response errors.' }
    end
  end

  # displays all Google Calendar events from calendar named Littlehumans except ignored ones 
  def show
    # obtain parsed Google Calendar API with pre-defined calendar id using key/secret
    @url_resp = ClientGoogle::client_google
    #logger.info("url_httparty response is *** #{@url_resp.to_json}") 
    #binding.pry
    respond_to do |format|
        format.json { render :json => @url_resp.to_json }
        format.html { redirect_to user_path(current_user), :notice => 'httparty response errors.' }
    end
  end

  # GET /rosters/new
  def new
    @roster = current_user.rosters.new
    @form_switch = "new event"
  end

  def edit
    @roster = current_user.rosters.new(roster_params)
  end

  # POST /rosters
  # POST /rosters.json
  def create 
    @roster = current_user.rosters.new(roster_params)

    respond_to do |format|
      if @roster.save
        format.html { redirect_to @roster, :notice => 'Roster was successfully created.' }
        format.json { render :action => "show", :status => :created, :location => @roster }
      else
        format.html { render :action => "new" }
        format.json { render :json => @roster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1
  # PATCH/PUT /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to @roster, :notice => 'Roster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => 'edit' }
        format.json { render :json => @roster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.json
  def destroy
    @roster.destroy

    respond_to do |format|
      format.html { redirect_to rosters_url }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def roster_params 
    # http://guides.rubyonrails.org/action_controller_overview.html#more-examples
    params.fetch(:roster, {}).permit(:name_shift, :name_location_hospital, :name_location_shift, :time_shift_start, :time_shift_end, :time_shift_duration)
  end
end

app/views/rosters/_form.html.erb
<!-- http://apidock.com/rails/ActionView/Helpers/FormHelper/form_for -->
<!-- form use depending on which function. parameter for each defined in controller -->
<% if @form_switch == "new event" %>
  <%= form_for(@roster, url: new_event_rosters_path, :method => 'post') do |f| %>
<%# else %>
  <%#= form_for(@roster, url: edit_event_rosters_path, :method => 'put') do |f| %>
<% end %>

  <% if @roster.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@roster.errors.count, "error") %> prohibited this roster from being saved:</h2>
    <ul>
      <% @roster.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label "Shift" %>&nbsp;&nbsp;
    <%= f.text_field :name_shift, :size => 39 %>
  </div>

  <div class="field">
    <%= f.label "Hospital" %>&nbsp;&nbsp;
    <%= f.text_field :name_location_hospital, :size => 36 %>
  </div>

  <div class="field">
    <%= f.label "Department" %>&nbsp;&nbsp;
    <%= f.text_field :name_location_shift, :size => 33 %>
  </div>

  <div class="field">
    <%= f.label "Start Time" %>&nbsp;&nbsp;
    <%= f.datetime_select :time_shift_start %>
  </div>

  <div class="field">
    <%= f.label "End Time" %>&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.datetime_select :time_shift_end %>
  </div>

  <div class="actions">
    <%= link_to "Back", :back, :class => "btn btn-default btn-lg active" %>&nbsp;

    <%= f.submit("Create", data: { :disable_with => "Please wait.." }, :class => "btn btn-lg btn-success") %>

    <% if @form_switch == "new event" %>
      <%= f.submit("Create", data: { :disable_with => "Please wait.." }, :class => "btn btn-lg btn-success") %>
    <%# else %>
      <%#= f.submit("Edit", data: { :disable_with => "Please wait.." }, :class => "btn btn-lg btn-success") %>
    <% end %>
  </div>
  
<% end %>

app/views/rosters/edit.html.erb
<br><br><br>

<h1>Edit Event</h1>

<%= render "form" %>

app/views/rosters/index.html.erb
<br><br><br>

<%= link_to "Back", :back, :class => "btn btn-default btn-lg active" %>&nbsp;

<!-- <div style="inline">
  <a href="mailto:ltfschoen@gmail.com" id="roster" class="btn btn-default btn-lg responsive">Request Permission</a>
</div>

<br>
Click the link above to be granted permission to join the Littlehumans Google Calendar. -->
<br><br>

<iframe src="https://www.google.com/calendar/embed?height=300&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=m88eksashs23rt5r00ji2vpn2g%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Australia%2FSydney" style=" border-width:0 " width="400" height="300" frameborder="0" scrolling="no"></iframe>

app/views/rosters/new.html.erb
<br><br><br>

<h1>New Event</h1>

<%= render "form" %>

app/views/rosters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name shift:</strong>
  <%= @roster.name_shift %>
</p>

<p>
  <strong>Name hospital:</strong>
  <%= @roster.name_hospital %>
</p>

<p>
  <strong>Name location:</strong>
  <%= @roster.name_location %>
</p>

<p>
  <strong>Time shift start:</strong>
  <%= @roster.time_shift_start %>
</p>

<p>
  <strong>Time shift end:</strong>
  <%= @roster.time_shift_end %>
</p>

<p>
  <strong>Time shift duration:</strong>
  <%= @roster.time_shift_duration %>
</p>

<%= link_to "Edit", edit_roster_path(@roster) %> |
<%= link_to "Back", rosters_path %>