config/routes.rb
LittlehumansApp::Application.routes.draw do

  resources :deliveries

  resources :rosters

  get "static_pages/about_us"
  get "static_pages/contact_us"
  get "static_pages/privacy"
  get "static_pages/terms_and_cond"
  get "static_pages/help"
  
  devise_for :users, 
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                               :registrations => "users/registrations", 
                               :passwords => 'users/passwords'
                             }

  # resources :users, :only => [:index, :show, :edit, :update]

  resources :users do
    resources :rosters
    resources :deliveries
  end

  resources :rosters do
    collection do
      post :new_event
      post :delete_event
    end
  end

  get "/dashboard" => "users#dashboard", :as => :dashboard

  devise_scope :user do
    root :to => "devise/sessions#new"
  # root :to => 'devise/sessions#new'
  #  get "/users/sign_in" => "devise/sessions#new", :as => :login
  #  get "/users/sign_up" => "devise/sessions#create", :as => :signup
  end

  # authenticated :user do
  #   root :to => "devise/sessions#new", :as => "authenticated_root"
  #   # Rails 4 users must specify the 'as' option to give it a unique name
  #   # root :to => "main#dashboard", :as => "authenticated_root"
  # end

  # tell devise to use scope users
  # devise_scope :user do
  #   root :to => 'devise/sessions#new'
  # end
end

app/views/shared/_footer.html.erb
<% provide(:title, "Footer") %>

<br>

<div class="footer navbar-fixed-bottom">
  <%= link_to "Privacy", static_pages_privacy_path %> |
  <%= link_to "Terms & Conditions", static_pages_terms_and_cond_path %><br>
  © 2014 Littlehumans by Luke Schoen.
</div>

app/views/shared/_meta.html.erb
<% content_for :head do %>

  <meta name="description" content="App for doctors, midwives, and nurses to record and share new born baby moments with parents via social media">
  <meta name="keywords" content="Midwife,Midwives,Doctor,Doctors,Nurse,Nurses,Baby, Babies,Child,Children,New Born,New Borns,Pregnancy,Labour,Parent,Parents,HTML,CSS,JavaScript,Rails,Ruby,jQuery,Javascript,OmniAuth,OAuth">
  <meta name="author" content="Luke Schoen">
  <meta charset="UTF-8">
  
<% end %>