config/routes.rb
LittlehumansApp::Application.routes.draw do

  resources :deliveries

  resources :rosters

  get "static_pages/about_us"
  get "static_pages/contact_us"
  get "static_pages/privacy"
  get "static_pages/terms_and_cond"
  get "static_pages/help"
  
  devise_for :users, 
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                               :registrations => "users/registrations", 
                               :passwords => 'users/passwords'
                             }

  # resources :users, :only => [:index, :show, :edit, :update]

  resources :users do
    resources :rosters
    resources :deliveries
  end

  resources :rosters do
    collection do
      post :new_event
      post :delete_event
    end
  end

  get "/dashboard" => "users#dashboard", :as => :dashboard

  devise_scope :user do
    root :to => "devise/sessions#new"
  # root :to => 'devise/sessions#new'
  #  get "/users/sign_in" => "devise/sessions#new", :as => :login
  #  get "/users/sign_up" => "devise/sessions#create", :as => :signup
  end

  # authenticated :user do
  #   root :to => "devise/sessions#new", :as => "authenticated_root"
  #   # Rails 4 users must specify the 'as' option to give it a unique name
  #   # root :to => "main#dashboard", :as => "authenticated_root"
  # end

  # tell devise to use scope users
  # devise_scope :user do
  #   root :to => 'devise/sessions#new'
  # end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base

  belongs_to :user
  belongs_to :roster

end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: [:show, :edit, :update, :destroy]

  # GET /deliveries
  # GET /deliveries.json
  def index   
    # display only babies created by logged in user if click the 'my' button
    if params[:filter] == 'my'
      @deliveries = current_user.deliveries.all if current_user.deliveries
      @all = false
    # otherwise display babies created by all users
    else 
      @deliveries = Delivery.all
      @all = true
    end
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
  end

  # GET /deliveries/new
  def new
    @delivery = current_user.deliveries.new
  end

  # GET /deliveries/1/edit
  def edit
  end

  # POST /deliveries
  # POST /deliveries.json
  def create
    @delivery = current_user.deliveries.new(delivery_params)

    respond_to do |format|
      if @delivery.save
        format.html { redirect_to @delivery, :notice => "Delivery was successfully created." }
        format.json { render :action => "show", :status => :created, :location => @delivery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @delivery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.html { redirect_to @delivery, :notice => "Delivery was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @delivery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_delivery
    @delivery = current_user.deliveries.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def delivery_params
    params.require(:delivery).permit(:name_baby, :time_born, :name_location_born)
  end
end

app/views/deliveries/_form.html.erb
<%= form_for(@delivery) do |f| %>

  <% if @delivery.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@delivery.errors.count, "error") %> prohibited this delivery from being saved:
    </h2>
    <ul>
      <% @delivery.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label "Baby Name" %>&nbsp;&nbsp;
    <%= f.text_field :name_baby, :size => 36 %>
  </div>

  <div class="field">
    <%= f.label "Date of Birth" %>&nbsp;&nbsp;
    <%= f.datetime_select :time_born %>
  </div>

  <div class="field">
    <%= f.label "Birthplace" %>&nbsp;&nbsp;
    <%= f.text_field :name_location_born, :size => 37 %>
  </div>

  <div class="actions">
    <%= link_to "Back", :back, :class => "btn btn-default btn-lg active" %>&nbsp;

    <%= f.submit("Create", data: { :disable_with => "Please wait.." }, :class => "btn btn-lg btn-success") %>
    <!-- <a href="#" id="create_event" class="btn btn-default btn-lg responsive">Create Event</a> -->
  </div>

<% end %>

app/views/deliveries/edit.html.erb
<br><br><br><br>

<div class="delivery-links">
  <%= link_to "Back", deliveries_path, :class => "btn btn-default btn-lg active" %>
</div>

<h1>Edit Baby</h1>

<%= render "form" %>

app/views/deliveries/index.html.erb
<br><br><br>

<div class="delivery-links">
  <%= link_to "Back", user_path(current_user), :class => "btn btn-default btn-lg active", :method => :get, :id => "make-new-delivery", :style => "width: 100%;" %> 
</div>

<div class="delivery-links">
  <%= link_to "Create", "/deliveries/new", :class => "btn btn-success btn-lg active", :method => :get, :id => "make-new-delivery", :style => "width: 100%;" %> 
</div>

<div class="delivery-links">
  <!-- fetch all deliveries -->
  <%= link_to "All", "/deliveries", :class => "btn btn-default btn-lg active", :method => :get, :id => "fetch-all-deliveries", :style => "width: 100%;" %> 
</div>

<div class="delivery-links">
  <%= link_to "My", "/deliveries?filter=my", :class => "btn btn-default btn-lg active", :method => :get, :id => "fetch-my-deliveries", :style => "width: 100%;" %> 
</div>

<% if @all == true %>
<h1>All Deliveries</h1>
<% elsif @all == false %>
<h1>My Deliveries</h1>
<% end %>

<table id="deliveries-list" class="table table-hover">

  <thead>
    <tr>
      <th class="delivery-centred">Baby Name</th>
      <th class="delivery-centred">DOB</th>
      <th class="delivery-centred">Birth Location</th>
      <th class="delivery-centred">Midwife & User ID</th>
      <% if @all == false %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody id="tbody">
    <% @deliveries.each do |delivery| %>
    <tr onclick="showDelivery(<%= delivery.id %>)">
      <a id="fake_click_<%= delivery.id %>" href="/deliveries/<%= delivery.id %>"></a>
      <td onmouseover="" style="cursor: pointer;"><%= delivery.name_baby %></td>
      <td onmouseover="" style="cursor: pointer;"><%= delivery.time_born %></td>
      <td onmouseover="" style="cursor: pointer;"><%= delivery.name_location_born %></td>
      <td onmouseover="" style="cursor: pointer;"><%= delivery.user.name if delivery.user %> <%= delivery.user.id if delivery.user %></td>
      <% if @all == false %> <!-- only let midwife user who created baby make changes -->
      <td><%= link_to "Destroy", delivery, :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "btn btn-default" %></td>
      <% end %>
    </tr>
    <% end %>
    User ID <%= current_user.id if current_user %>
  </tbody>

</table>

<!-- jQuery functions display list of deliveries (babies) -->
<%= javascript_include_tag "deliveries.js" %>

app/views/deliveries/new.html.erb
<br><br><br>

<h1>New Baby</h1>

<%= render "form" %>

app/views/deliveries/show.html.erb
<br><br><br><br>

<div class="delivery-links">
  <%= link_to "Back", deliveries_path, :class => "btn btn-default btn-lg active" %>
</div>

<p id="notice"><%= notice %></p>

<h1>Baby Details</h1>

<table id="deliveries-list" class="table table-hover">

  <thead>
    <tr>
      <th class="delivery-centred">Baby Name</th>
      <th class="delivery-centred">DOB</th>
      <th class="delivery-centred">Birth Location</th>
      <th class="delivery-centred">Midwife</th>
      <th></th>
    </tr>
  </thead>

  <tbody id="tbody">
    <tr>
      <td><%= @delivery.name_baby %></td>
      <td><%= @delivery.time_born %></td>
      <td><%= @delivery.name_location_born %></td>
      <td><%= @delivery.user.name if @delivery.user %></td>
      <td><%= link_to "Edit", edit_delivery_path(@delivery), :class => "btn btn-default" %></td>
      <td><%= link_to "Destroy", @delivery, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-default" %></td>
    </tr>
  </tbody>
  
</table>