config/routes.rb
LittlehumansApp::Application.routes.draw do

  resources :deliveries

  resources :rosters

  get "static_pages/about_us"
  get "static_pages/contact_us"
  get "static_pages/privacy"
  get "static_pages/terms_and_cond"
  get "static_pages/help"
  
  devise_for :users, 
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                               :registrations => "users/registrations", 
                               :passwords => 'users/passwords'
                             }

  # resources :users, :only => [:index, :show, :edit, :update]

  resources :users do
    resources :rosters
    resources :deliveries
  end

  resources :rosters do
    collection do
      post :new_event
      post :delete_event
    end
  end

  get "/dashboard" => "users#dashboard", :as => :dashboard

  devise_scope :user do
    root :to => "devise/sessions#new"
  # root :to => 'devise/sessions#new'
  #  get "/users/sign_in" => "devise/sessions#new", :as => :login
  #  get "/users/sign_up" => "devise/sessions#create", :as => :signup
  end

  # authenticated :user do
  #   root :to => "devise/sessions#new", :as => "authenticated_root"
  #   # Rails 4 users must specify the 'as' option to give it a unique name
  #   # root :to => "main#dashboard", :as => "authenticated_root"
  # end

  # tell devise to use scope users
  # devise_scope :user do
  #   root :to => 'devise/sessions#new'
  # end
end

app/views/layouts/__application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>LittlehumansApp</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!-- shared partial meta included in below -->
  <% if content_for?(:head) %>
    <%= yield(:head) %>
  <% end %>
  <%= csrf_meta_tags %>

  <% if controller_name == 'sessions' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <% end %>

</head>

<body id="site-container" class="<%= 'show_background' if controller_name == 'sessions' %>">

  <header id="header">

    <nav id="nav-menu" class="navbar navbar-default nav_init navbar-fixed-top" role="navigation" style="background-color:#6EBFDB">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" style="color:#FAFA16"><i style="font-family: 'Lemon', cursive;"><em>Littlehumans</em></i></a> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/"><i class="glyphicon glyphicon-home"></i></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if !user_signed_in? %>
            <li><%= link_to "Login", new_user_session_path  %></li> 
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% else %>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Info <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Help', static_pages_help_path %></li>
            <li><%= link_to 'About Us', static_pages_about_us_path%></li> <!-- 'http://lukeschoen.blogspot.com', target: 'new' %></li>  -->
            <li><%= link_to 'Contact Us', static_pages_contact_us_path %></li>
          </ul>
        </li>
      </ul>
    </div>  

    <!-- do not display search bar if no user logged in -->
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse navbar-ex1-collapse" style="overflow-x: hidden;" >
      <ul class="nav navbar-nav">
        <li>
          <form class="navbar-form">
            &nbsp;&nbsp;&nbsp;<input type="text" style="width: 70%; display:inline-block;" class="form-control" placeholder="Search">
            <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
          </form>
        </li>
      </ul>
    </div>
    <% end %>

  </nav>

</header>

<div id="container">

  <%= yield %>

</div>

<footer style="text-align: center;">

  <%= render partial:'/shared/footer' %>

  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>

</footer>

<!-- load google google analytics from application_helper.rb -->
<!-- http://subratrout.com/blog/adding-google-analytics-to-a-rails-app/ -->
<% if Rails.env.production? %>

<script>

  $("document").ready(function() {
    // load google-analytics
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); 
    ga('create', 'UA-49241480-1', 'littlehumans.herokuapp.com');
    ga('send', 'pageview');
  });

</script>

<% end %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>LittlehumansApp</title>

  <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!-- shared partial meta included in below -->
  <% if content_for?(:head) %>
    <%= yield(:head) %>
  <% end %>
  <%= csrf_meta_tags %>

  <% if controller_name == "sessions" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <% end %>

</head>

<body id="site-container" class="<%= 'show_background' if controller_name == 'sessions' %>">

  <header id="header">

    <nav id="nav-menu" class="navbar navbar-default nav_init navbar-fixed-top" role="navigation" style="background-color:#6EBFDB">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" style="color:#FAFA16"><i style="font-family: 'Lemon', cursive;"><em>Littlehumans</em></i></a> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/"><i class="glyphicon glyphicon-home"></i></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if !user_signed_in? %>
            <li><%= link_to "Login", new_user_session_path  %></li> 
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% else %>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Info <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Help", static_pages_help_path %></li>
            <li><%= link_to "About Us", static_pages_about_us_path%></li> <!-- 'http://lukeschoen.blogspot.com', target: 'new' %></li>  -->
            <li><%= link_to "Contact Us", static_pages_contact_us_path %></li>
          </ul>
        </li>
      </ul>
    </div>  

    <!-- do not display search bar if no user logged in -->
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse navbar-ex1-collapse" style="overflow-x: hidden;" >
      <ul class="nav navbar-nav">
        <li>
          <form class="navbar-form">
            &nbsp;&nbsp;&nbsp;<input type="text" style="width: 70%; display:inline-block;" class="form-control" placeholder="Search">
            <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
          </form>
        </li>
      </ul>
    </div>
    <% end %>

  </nav>

</header>

<div id="container">

  <%= yield %>

</div>

<footer style="text-align: center;">

  <%= render :partial => "/shared/footer" %>

  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>

</footer>

<!-- load google google analytics from application_helper.rb -->
<!-- http://subratrout.com/blog/adding-google-analytics-to-a-rails-app/ -->
<% if Rails.env.production? %>

<script>

  $("document").ready(function() {
    // load google-analytics
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); 
    ga('create', 'UA-49241480-1', 'littlehumans.herokuapp.com');
    ga('send', 'pageview');
  });

</script>

<% end %>

</body>
</html>